version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: lamungu/udacity-cp-reverseproxy 
  backend_user:
    build:
      context: ../../user-service
    image: lamungu/udacity-cp-user-service
  frontend:
    build:
      context: ../../frontend  
    image: lamungu/udacity-cp-frontend
